// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-J4Fs6QelMQNMaZKMLgbUZcu-cIPBflo',
    appId: '1:95280475222:web:12cec8ff37cadab4419ff7',
    messagingSenderId: '95280475222',
    projectId: 'instagram-b1f8a',
    authDomain: 'instagram-b1f8a.firebaseapp.com',
    storageBucket: 'instagram-b1f8a.appspot.com',
    measurementId: 'G-STEGQL54S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NfEoKM3COrbAmbyffL-i2UT3fkWDcig',
    appId: '1:95280475222:android:53d060da5e55142c419ff7',
    messagingSenderId: '95280475222',
    projectId: 'instagram-b1f8a',
    storageBucket: 'instagram-b1f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdblXwOr1hi5z4pKkcRGTqzkLcpwlvJg',
    appId: '1:95280475222:ios:683f464136c7c7a6419ff7',
    messagingSenderId: '95280475222',
    projectId: 'instagram-b1f8a',
    storageBucket: 'instagram-b1f8a.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdblXwOr1hi5z4pKkcRGTqzkLcpwlvJg',
    appId: '1:95280475222:ios:d225ef296a98237e419ff7',
    messagingSenderId: '95280475222',
    projectId: 'instagram-b1f8a',
    storageBucket: 'instagram-b1f8a.appspot.com',
    iosBundleId: 'com.example.flutterInstagramClone.RunnerTests',
  );
}
